<?php
// $Id: template.view-colspans.inc,v 1.2 2011/07/07 11:16:44 sebastien.millart Exp $

/*	*
	* @file template.view-colspans.inc
	* Colspans array used with the wiews-wiew-table.tpl.php template.
	*
	*/

	$colspans = array(
		0 => NULL
//		########## 1 COLUMN TEMPLATE ##########
	,	1 => array(
			'0'
//		Highlight Region Colspans (display block):
		,	'highlight-colspans-16' => array('16')
//		Before Content Region Colspans (display page):
		,	'before-content-colspans-8' => array('8')
//		Content Region Colspans (display page):
		,	'content-colspans-16' => array('16')
//		Right Sidebar Region Colspans (display page):
		,	'right-sidebar-colspans-5' => array('5')
		)
//		########## 2 COLUMNS TEMPLATE ##########
	,	2 => array(
			'0'
		,	'0'
//		Before Content Region Colspans - Grid 11 cols (display block):
		,	'before-content-colspans-1-10' => array('1', '10')
		,	'before-content-colspans-2-9' => array('2', '9')
		,	'before-content-colspans-3-8' => array('3', '8')
		,	'before-content-colspans-4-7' => array('4', '7')
		,	'before-content-colspans-5-6' => array('5', '6')
		,	'before-content-colspans-6-5' => array('6', '5')
		,	'before-content-colspans-7-4' => array('7', '4')
		,	'before-content-colspans-8-3' => array('8', '3')
		,	'before-content-colspans-9-2' => array('9', '2')
		,	'before-content-colspans-10-1' => array('10', '1')
//		Before Content Region Colspans - Grid 8 cols (display block):
		,	'before-content-colspans-1-7' => array('1', '7')
		,	'before-content-colspans-2-6' => array('2', '6')
		,	'before-content-colspans-3-5' => array('3', '5')
		,	'before-content-colspans-4-4' => array('4', '4')
		,	'before-content-colspans-5-3' => array('5', '3')
		,	'before-content-colspans-6-2' => array('6', '2')
		,	'before-content-colspans-7-1' => array('7', '1')
//		Content Region Colspans - Grid 16 cols (display page):
		,	'content-colspans-1-15' => array('1', '15')
		,	'content-colspans-2-14' => array('2', '14')
		,	'content-colspans-3-13' => array('3', '13')
		,	'content-colspans-4-12' => array('4', '12')
		,	'content-colspans-5-11' => array('5', '11')
		,	'content-colspans-6-10' => array('6', '10')
		,	'content-colspans-7-9' => array('7', '9')
		,	'content-colspans-8-8' => array('8', '8')
		,	'content-colspans-9-7' => array('9', '7')
		,	'content-colspans-10-6' => array('10', '6')
		,	'content-colspans-11-5' => array('11', '5')
		,	'content-colspans-12-4' => array('12', '4')
		,	'content-colspans-13-3' => array('13', '3')
		,	'content-colspans-14-2' => array('14', '2')
		,	'content-colspans-15-1' => array('15', '1')
//		Content Region Colspans - Grid 8 cols (display block):
		,	'content-colspans-1-7' => array('1', '7')
		,	'content-colspans-2-6' => array('2', '6')
		,	'content-colspans-3-5' => array('3', '5')
		,	'content-colspans-4-4' => array('4', '4')
		,	'content-colspans-5-3' => array('5', '3')
		,	'content-colspans-6-2' => array('6', '2')
		,	'content-colspans-7-1' => array('7', '1')
//		After Content Region Colspans - Grid 11 cols (display block):
		,	'after-content-colspans-1-10' => array('1', '10')
		,	'after-content-colspans-2-9' => array('2', '9')
		,	'after-content-colspans-3-8' => array('3', '8')
		,	'after-content-colspans-4-7' => array('4', '7')
		,	'after-content-colspans-5-6' => array('5', '6')
		,	'after-content-colspans-6-5' => array('6', '5')
		,	'after-content-colspans-7-4' => array('7', '4')
		,	'after-content-colspans-8-3' => array('8', '3')
		,	'after-content-colspans-9-2' => array('9', '2')
		,	'after-content-colspans-10-1' => array('10', '1')
//		After Content Region Colspans - Grid 5 cols (Recommended Items, Editor's Choice) - (display block):
		,	'after-content-colspans-1-4' => array('1', '4')
//		After Content Region Colspans - Grid 6 cols (Next Events) - (display block):
		,	'after-content-colspans-1-5' => array('1', '5')
//		After Content Region Colspans - Grid 8 cols (display block):
		,	'after-content-colspans-1-7' => array('1', '7')
		,	'after-content-colspans-2-6' => array('2', '6')
		,	'after-content-colspans-3-5' => array('3', '5')
		,	'after-content-colspans-5-4' => array('4', '4')
		,	'after-content-colspans-6-3' => array('5', '3')
		,	'after-content-colspans-7-2' => array('6', '2')
		,	'after-content-colspans-8-1' => array('7', '1')
//		Right Sidebar Region Colspans - Grid 5 cols (display block):
		,	'right-sidebar-colspans-1-4' => array('1', '4')
		,	'right-sidebar-colspans-2-3' => array('2', '3')
		,	'right-sidebar-colspans-3-2' => array('3', '2')
		,	'right-sidebar-colspans-4-1' => array('4', '1')
		)
//		########## 3 COLUMNS TEMPLATE ##########
	,	3 => array(
			'0'
		,	'0'
		,	'0'
		)
	);

?>